# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'
target 'CommunicationUI-Proxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommunicationUI-Proxy
  pod 'AzureCommunicationUICalling', '1.14.0'

end
