# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
target 'CommunicationUI-Proxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommunicationUI-Proxy
  pod 'AzureCommunicationUICalling', '1.8.0-beta.1'

end
